/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import projeto.*;

/**
 *
 * @author Wallace
 */
public class telaMatriz extends javax.swing.JFrame {

    /**
     * Creates new form telaMatriz
     */
    public telaMatriz() {
        initComponents();
    }
    
    Matriz matriz = new Matriz();
    
    public void clicks(javax.swing.JToggleButton botao, java.awt.event.MouseEvent evt, int i, int j){
        Celula cell = matriz.getCelulas()[i][j];
        String tipo = cell.getTipo();
        
        if (evt.getButton() == 1){
            if (tipo.equals("Bomba")){
                Bomba bomba = (Bomba) cell;
                botao.setIcon(bomba.mostrarImagem());
            }
            else{
                Numero numero = (Numero) cell;
                botao.setIcon(numero.mostrarImagem());
            }
            botao.setEnabled(false);
        }
        else if(evt.getButton() == 3 && botao.isEnabled()){
            if (cell.getBandeira()){
                botao.setIcon(null);
            }
            else{
                botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flag.png")));
            }
            cell.invertBandeira();
        };
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(320, 320));
        getContentPane().setLayout(new java.awt.GridLayout(5, 5, 1, 1));

        jToggleButton1.setToolTipText("");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton1);

        jToggleButton2.setToolTipText("");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton2);

        jToggleButton3.setToolTipText("");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton3);

        jToggleButton4.setToolTipText("");
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton4);

        jToggleButton5.setToolTipText("");
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton5);

        jToggleButton6.setToolTipText("");
        jToggleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton6);

        jToggleButton7.setToolTipText("");
        jToggleButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton7MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton7);

        jToggleButton8.setToolTipText("");
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton8);

        jToggleButton9.setToolTipText("");
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton9MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton9);

        jToggleButton10.setToolTipText("");
        jToggleButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton10MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton10);

        jToggleButton11.setToolTipText("");
        jToggleButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton11MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton11);

        jToggleButton12.setToolTipText("");
        jToggleButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton12MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton12);

        jToggleButton13.setToolTipText("");
        jToggleButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton13MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton13);

        jToggleButton14.setToolTipText("");
        jToggleButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton14MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton14);

        jToggleButton15.setToolTipText("");
        jToggleButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton15MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton15);

        jToggleButton16.setToolTipText("");
        jToggleButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton16MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton16);

        jToggleButton17.setToolTipText("");
        jToggleButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton17MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton17);

        jToggleButton18.setToolTipText("");
        jToggleButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton18MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton18);

        jToggleButton19.setToolTipText("");
        jToggleButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton19MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton19);

        jToggleButton20.setToolTipText("");
        jToggleButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton20MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton20);

        jToggleButton21.setToolTipText("");
        jToggleButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton21MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton21);

        jToggleButton22.setToolTipText("");
        jToggleButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton22MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton22);

        jToggleButton23.setToolTipText("");
        jToggleButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton23MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton23);

        jToggleButton24.setToolTipText("");
        jToggleButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton24MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton24);

        jToggleButton25.setToolTipText("");
        jToggleButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton25MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        clicks(jToggleButton1, evt, 0, 0);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        clicks(jToggleButton2, evt, 0, 1);
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        clicks(jToggleButton3, evt, 0, 2);
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        clicks(jToggleButton4, evt, 0, 3);
    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseClicked
        clicks(jToggleButton5, evt, 0, 4);
    }//GEN-LAST:event_jToggleButton5MouseClicked

    private void jToggleButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MouseClicked
        clicks(jToggleButton6, evt, 1, 0);
    }//GEN-LAST:event_jToggleButton6MouseClicked

    private void jToggleButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton7MouseClicked
        clicks(jToggleButton7, evt, 1, 1);
    }//GEN-LAST:event_jToggleButton7MouseClicked

    private void jToggleButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MouseClicked
        clicks(jToggleButton8, evt, 1, 2);
    }//GEN-LAST:event_jToggleButton8MouseClicked

    private void jToggleButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton9MouseClicked
        clicks(jToggleButton9, evt, 1, 3);
    }//GEN-LAST:event_jToggleButton9MouseClicked

    private void jToggleButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton10MouseClicked
        clicks(jToggleButton10, evt, 1, 4);
    }//GEN-LAST:event_jToggleButton10MouseClicked

    private void jToggleButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton11MouseClicked
        clicks(jToggleButton11, evt, 2, 0);
    }//GEN-LAST:event_jToggleButton11MouseClicked

    private void jToggleButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton12MouseClicked
        clicks(jToggleButton12, evt, 2, 1);
    }//GEN-LAST:event_jToggleButton12MouseClicked

    private void jToggleButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton13MouseClicked
        clicks(jToggleButton13, evt, 2, 2);
    }//GEN-LAST:event_jToggleButton13MouseClicked

    private void jToggleButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton14MouseClicked
        clicks(jToggleButton14, evt, 2, 3);
    }//GEN-LAST:event_jToggleButton14MouseClicked

    private void jToggleButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton15MouseClicked
        clicks(jToggleButton15, evt, 2, 4);
    }//GEN-LAST:event_jToggleButton15MouseClicked

    private void jToggleButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton16MouseClicked
        clicks(jToggleButton16, evt, 3, 0);
    }//GEN-LAST:event_jToggleButton16MouseClicked

    private void jToggleButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton17MouseClicked
        clicks(jToggleButton17, evt, 3, 1);
    }//GEN-LAST:event_jToggleButton17MouseClicked

    private void jToggleButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton18MouseClicked
        clicks(jToggleButton18, evt, 3, 2);
    }//GEN-LAST:event_jToggleButton18MouseClicked

    private void jToggleButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton19MouseClicked
        clicks(jToggleButton19, evt, 3, 3);
    }//GEN-LAST:event_jToggleButton19MouseClicked

    private void jToggleButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton20MouseClicked
        clicks(jToggleButton20, evt, 3, 4);
    }//GEN-LAST:event_jToggleButton20MouseClicked

    private void jToggleButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton21MouseClicked
        clicks(jToggleButton21, evt, 4, 0);
    }//GEN-LAST:event_jToggleButton21MouseClicked

    private void jToggleButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton22MouseClicked
        clicks(jToggleButton22, evt, 4, 1);
    }//GEN-LAST:event_jToggleButton22MouseClicked

    private void jToggleButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton23MouseClicked
        clicks(jToggleButton23, evt, 4, 2);
    }//GEN-LAST:event_jToggleButton23MouseClicked

    private void jToggleButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton24MouseClicked
        clicks(jToggleButton24, evt, 4, 3);
    }//GEN-LAST:event_jToggleButton24MouseClicked

    private void jToggleButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton25MouseClicked
        clicks(jToggleButton25, evt, 4, 4);
    }//GEN-LAST:event_jToggleButton25MouseClicked
                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
