/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import projeto.*;

/**
 *
 * @author Wallace
 */
public class telaMatriz extends javax.swing.JFrame {
    private final Principal mae;
    /**
     * Creates new form telaMatriz
     */
    public telaMatriz(Principal telaprincipal) {
        initComponents();
        this.mae = telaprincipal;
    }
    
    Matriz matriz = new Matriz();
    
    public void clicks(javax.swing.JToggleButton botao, java.awt.event.MouseEvent evt, int i, int j){
        Celula cell = matriz.getCelulas()[i][j];
        String tipo = cell.getTipo();
        
        if (evt.getButton() == 1){
            if (tipo.equals("Bomba")){
                Bomba bomba = (Bomba) cell;
                botao.setIcon(bomba.mostrarImagem());
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Você perdeu :(", "Derrota", javax.swing.JOptionPane.ERROR_MESSAGE);
                this.setVisible(false);
                mae.regeneraTela();
            }
            else{
                Numero numero = (Numero) cell;
                botao.setIcon(numero.mostrarImagem());
            }
            botao.setEnabled(false);
        }
        else if(evt.getButton() == 3 && botao.isEnabled()){
            if (cell.getBandeira()){
                botao.setIcon(null);
            }
            else{
                botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flag.png")));
            }
            cell.invertBandeira();
        };
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.GridLayout(5, 5, 1, 1));

        jToggleButton1.setToolTipText(null);
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton1MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton1);

        jToggleButton2.setToolTipText(null);
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton2MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton2);

        jToggleButton3.setToolTipText(null);
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton3MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton3);

        jToggleButton4.setToolTipText(null);
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton4MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton4);

        jToggleButton5.setToolTipText(null);
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton5MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton5);

        jToggleButton6.setToolTipText(null);
        jToggleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton6MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton6);

        jToggleButton7.setToolTipText(null);
        jToggleButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton7MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton7);

        jToggleButton8.setToolTipText(null);
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton8MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton8);

        jToggleButton9.setToolTipText(null);
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton9MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton9);

        jToggleButton10.setToolTipText(null);
        jToggleButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton10MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton10);

        jToggleButton11.setToolTipText(null);
        jToggleButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton11MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton11);

        jToggleButton12.setToolTipText(null);
        jToggleButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton12MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton12);

        jToggleButton13.setToolTipText(null);
        jToggleButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton13MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton13);

        jToggleButton14.setToolTipText(null);
        jToggleButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton14MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton14);

        jToggleButton15.setToolTipText(null);
        jToggleButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton15MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton15);

        jToggleButton16.setToolTipText(null);
        jToggleButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton16MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton16);

        jToggleButton17.setToolTipText(null);
        jToggleButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton17MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton17);

        jToggleButton18.setToolTipText(null);
        jToggleButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton18MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton18);

        jToggleButton19.setToolTipText(null);
        jToggleButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton19MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton19);

        jToggleButton20.setToolTipText(null);
        jToggleButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton20MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton20);

        jToggleButton21.setToolTipText(null);
        jToggleButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton21MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton21);

        jToggleButton22.setToolTipText(null);
        jToggleButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton22MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton22);

        jToggleButton23.setToolTipText(null);
        jToggleButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton23MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton23);

        jToggleButton24.setToolTipText(null);
        jToggleButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton24MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton24);

        jToggleButton25.setToolTipText(null);
        jToggleButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleButton25MousePressed(evt);
            }
        });
        getContentPane().add(jToggleButton25);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MousePressed
        clicks(jToggleButton1, evt, 0, 0);
    }//GEN-LAST:event_jToggleButton1MousePressed

    private void jToggleButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MousePressed
        clicks(jToggleButton2, evt, 0, 1);
    }//GEN-LAST:event_jToggleButton2MousePressed

    private void jToggleButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MousePressed
        clicks(jToggleButton3, evt, 0, 2);
    }//GEN-LAST:event_jToggleButton3MousePressed

    private void jToggleButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MousePressed
        clicks(jToggleButton4, evt, 0, 3);
    }//GEN-LAST:event_jToggleButton4MousePressed

    private void jToggleButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MousePressed
        clicks(jToggleButton5, evt, 0, 4);
    }//GEN-LAST:event_jToggleButton5MousePressed

    private void jToggleButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MousePressed
        clicks(jToggleButton6, evt, 1, 0);
    }//GEN-LAST:event_jToggleButton6MousePressed

    private void jToggleButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton7MousePressed
        clicks(jToggleButton7, evt, 1, 1);
    }//GEN-LAST:event_jToggleButton7MousePressed

    private void jToggleButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MousePressed
        clicks(jToggleButton8, evt, 1, 2);
    }//GEN-LAST:event_jToggleButton8MousePressed

    private void jToggleButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton9MousePressed
        clicks(jToggleButton9, evt, 1, 3);
    }//GEN-LAST:event_jToggleButton9MousePressed

    private void jToggleButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton10MousePressed
        clicks(jToggleButton10, evt, 1, 4);
    }//GEN-LAST:event_jToggleButton10MousePressed

    private void jToggleButton11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton11MousePressed
        clicks(jToggleButton11, evt, 2, 0);
    }//GEN-LAST:event_jToggleButton11MousePressed

    private void jToggleButton12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton12MousePressed
        clicks(jToggleButton12, evt, 2, 1);
    }//GEN-LAST:event_jToggleButton12MousePressed

    private void jToggleButton13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton13MousePressed
        clicks(jToggleButton13, evt, 2, 2);
    }//GEN-LAST:event_jToggleButton13MousePressed

    private void jToggleButton14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton14MousePressed
        clicks(jToggleButton14, evt, 2, 3);
    }//GEN-LAST:event_jToggleButton14MousePressed

    private void jToggleButton15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton15MousePressed
        clicks(jToggleButton15, evt, 2, 4);
    }//GEN-LAST:event_jToggleButton15MousePressed

    private void jToggleButton16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton16MousePressed
        clicks(jToggleButton16, evt, 3, 0);
    }//GEN-LAST:event_jToggleButton16MousePressed

    private void jToggleButton17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton17MousePressed
        clicks(jToggleButton17, evt, 3, 1);
    }//GEN-LAST:event_jToggleButton17MousePressed

    private void jToggleButton18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton18MousePressed
        clicks(jToggleButton18, evt, 3, 2);
    }//GEN-LAST:event_jToggleButton18MousePressed

    private void jToggleButton19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton19MousePressed
        clicks(jToggleButton19, evt, 3, 3);
    }//GEN-LAST:event_jToggleButton19MousePressed

    private void jToggleButton20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton20MousePressed
        clicks(jToggleButton20, evt, 3, 4);
    }//GEN-LAST:event_jToggleButton20MousePressed

    private void jToggleButton21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton21MousePressed
        clicks(jToggleButton21, evt, 4, 0);
    }//GEN-LAST:event_jToggleButton21MousePressed

    private void jToggleButton22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton22MousePressed
        clicks(jToggleButton22, evt, 4, 1);
    }//GEN-LAST:event_jToggleButton22MousePressed

    private void jToggleButton23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton23MousePressed
        clicks(jToggleButton23, evt, 4, 2);
    }//GEN-LAST:event_jToggleButton23MousePressed

    private void jToggleButton24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton24MousePressed
        clicks(jToggleButton24, evt, 4, 3);
    }//GEN-LAST:event_jToggleButton24MousePressed

    private void jToggleButton25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton25MousePressed
        clicks(jToggleButton25, evt, 4, 4);
    }//GEN-LAST:event_jToggleButton25MousePressed
                                             

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
